### ISSUE TITLE
 版本比对是如何进行的？

### ISSUE THREAD

**Issue by icukeup** [momosecurity/mosec-x-plugin-backend#1]
你好，

    通过阅读代码，发现代码中采用版本比对的方式与md文档中描述的比对流程不符，请问目前代码中采用的比对方式可否保证比对结果的准确性呢？

此外，对于漏洞库规则，是如何进行数据标准化处理的呢？可否开源数据处理代码呢？

**Comment by retanoj** [comment]
“发现代码中采用版本比对的方式与md文档中描述的比对流程不符”，代码优化进度可能超前于README，还请以代码为准。
“请问目前代码中采用的比对方式可否保证比对结果的准确性呢？”，如发现bug，请给出具体问题，场景以及数据，谢谢。
“对于漏洞库规则，是如何进行数据标准化处理的呢？”，对于组件具体版本没有做处理，对于漏洞规则中的范围版本，以README中“漏洞规则数据表”为准。
“可否开源数据处理代码呢？”，抱歉，这个目前不可行。

**Comment by retanoj** [comment]
先关闭issue了。如有问题，欢迎继续讨论。
